### PR TITLE
Fix for issue #77

### LINKED ISSUE #77: UTF characters not rendered correctly in plugin information
### Description of the Issue
UTF characters in the plugin information are not rendered correctly in plugin manager when the plugin is viewed (for example, when trying to install a new plugin).

The author of the [Npp Xml Treeview](https://github.com/joaoasrosa/nppxmltreeview/search?utf8=%E2%9C%93&q=rosa&type=) plugin is `João Rosa`  but this is shown in Plugin Manager as `JoÃ£o Rosa`

image

The plugin still installs and works as expected, so this is a minor issue.

### Version Information
Plugin manager version : 1.4.9.0 (x64)
Notepad++ version: 7.4.2 (x64)
OS: Windows 10 1703 Enterprise (x64)

### PR DESCRIPTION
**Pull request by chcg**
- transform UTF-8 input from xml properly to windows UTF-16 to fix #77 
- correct parser for TCHAR unicode usage by _istspace() instead of isspace() and L''
- cleanup of appveyor.yml

### CODE REVIEW

File: TinyXml/src/tinyxmlparser.cpp [hunk 1]
```diff
@@ -334,12 +334,12 @@ const TCHAR* TiXmlBase::ReadText(	const TCHAR* p,
 		while (	   p && *p
 				&& !StringEqual( p, endTag, caseInsensitive ) )
 		{
-			if ( *p == '\r' || *p == '\n' )
+			if ( *p == L'\r' || *p == L'\n' )
```
Comment (MAPJe71) [inline TinyXml/src/tinyxmlparser.cpp]: Use `TEXT('\r')` and `TEXT('\n')` as `*p` is of type `TCHAR`.

Comment (chcg) [reply TinyXml/src/tinyxmlparser.cpp]: @MAPJe71 As PluginManager just supports the unicode build that makes no difference as TEXT() equals in this case L, but for a clean codebase and to be in sync with the surrounding code I have corrected that with https://github.com/bruderstein/nppPluginManager/commit/1a02cf1e8a1fcc8f7f4d2528f45d0270c3b5a6a6

Thanks for the review.
